# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_remove_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='likes_users', through='myapp.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
