# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='vredina.jpg', upload_to=b''),
            preserve_default=False,
        ),
    ]
